apiVersion: apps/v1
kind: Deployment
metadata:
  name: carSales
  labels:
    app: carSales
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carSales
  template:
    metadata:
      labels:
        app: carSales
    spec:
      containers:
        - name: carSales
          image: username/carSales:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5